import type { AoeShape } from "./types";

export interface SpellAoe {
  name: string;
  shape: AoeShape;
  sizeFt: number;
  widthFt: number;
  color: string;
}

// Generated from the 5etools spell data: every spell with a parseable
// area of effect, colored by its primary damage type. A few spells whose
// area cannot be parsed automatically (e.g. Wall of Fire's line/ring forms)
// are hand-added and kept in alphabetical order.
export const SPELL_AOES: SpellAoe[] = [
  { name: "Abi-Dalzim's Horrid Wilting", shape: "square", sizeFt: 30, widthFt: 5, color: "#7a33aa" },
  { name: "Aganazzar's Scorcher", shape: "line", sizeFt: 30, widthFt: 5, color: "#ff4400" },
  { name: "Alarm", shape: "square", sizeFt: 20, widthFt: 5, color: "#44aaff" },
  { name: "Antilife Shell", shape: "circle", sizeFt: 10, widthFt: 5, color: "#44aaff" },
  { name: "Antimagic Field", shape: "circle", sizeFt: 10, widthFt: 5, color: "#44aaff" },
  { name: "Antipathy/Sympathy", shape: "square", sizeFt: 200, widthFt: 5, color: "#44aaff" },
  { name: "Arms of Hadar", shape: "circle", sizeFt: 10, widthFt: 5, color: "#7a33aa" },
  { name: "Aura of Life", shape: "circle", sizeFt: 30, widthFt: 5, color: "#44aaff" },
  { name: "Aura of Purity", shape: "circle", sizeFt: 30, widthFt: 5, color: "#44aaff" },
  { name: "Aura of Vitality", shape: "circle", sizeFt: 30, widthFt: 5, color: "#44aaff" },
  { name: "Burning Hands", shape: "cone", sizeFt: 15, widthFt: 5, color: "#ff4400" },
  { name: "Call Lightning", shape: "circle", sizeFt: 60, widthFt: 5, color: "#f5d90a" },
  { name: "Calm Emotions", shape: "circle", sizeFt: 20, widthFt: 5, color: "#44aaff" },
  { name: "Circle of Death", shape: "circle", sizeFt: 60, widthFt: 5, color: "#7a33aa" },
  { name: "Circle of Power", shape: "circle", sizeFt: 30, widthFt: 5, color: "#44aaff" },
  { name: "Cloudkill", shape: "circle", sizeFt: 20, widthFt: 5, color: "#33aa33" },
  { name: "Color Spray", shape: "cone", sizeFt: 15, widthFt: 5, color: "#44aaff" },
  { name: "Cone of Cold", shape: "cone", sizeFt: 60, widthFt: 5, color: "#66ccff" },
  { name: "Confusion", shape: "circle", sizeFt: 10, widthFt: 5, color: "#44aaff" },
  { name: "Conjure Barrage", shape: "cone", sizeFt: 60, widthFt: 5, color: "#44aaff" },
  { name: "Conjure Celestial", shape: "circle", sizeFt: 10, widthFt: 5, color: "#ffe066" },
  { name: "Conjure Volley", shape: "circle", sizeFt: 40, widthFt: 5, color: "#44aaff" },
  { name: "Control Flames", shape: "square", sizeFt: 5, widthFt: 5, color: "#44aaff" },
  { name: "Control Winds", shape: "square", sizeFt: 100, widthFt: 5, color: "#44aaff" },
  { name: "Create Bonfire", shape: "square", sizeFt: 5, widthFt: 5, color: "#ff4400" },
  { name: "Create or Destroy Water", shape: "square", sizeFt: 30, widthFt: 5, color: "#44aaff" },
  { name: "Crusader's Mantle", shape: "circle", sizeFt: 30, widthFt: 5, color: "#ffe066" },
  { name: "Darkness", shape: "circle", sizeFt: 15, widthFt: 5, color: "#44aaff" },
  { name: "Dawn", shape: "circle", sizeFt: 30, widthFt: 5, color: "#ffe066" },
  { name: "Daylight", shape: "circle", sizeFt: 60, widthFt: 5, color: "#44aaff" },
  { name: "Delayed Blast Fireball", shape: "circle", sizeFt: 20, widthFt: 5, color: "#ff4400" },
  { name: "Destructive Wave", shape: "circle", sizeFt: 30, widthFt: 5, color: "#7a33aa" },
  { name: "Doomtide", shape: "circle", sizeFt: 20, widthFt: 5, color: "#ff66cc" },
  { name: "Dragon's Breath", shape: "cone", sizeFt: 15, widthFt: 5, color: "#66cc00" },
  { name: "Druid Grove", shape: "square", sizeFt: 30, widthFt: 5, color: "#44aaff" },
  { name: "Earthquake", shape: "circle", sizeFt: 100, widthFt: 5, color: "#aaaaaa" },
  { name: "Erupting Earth", shape: "square", sizeFt: 20, widthFt: 5, color: "#aaaaaa" },
  { name: "Faerie Fire", shape: "circle", sizeFt: 10, widthFt: 5, color: "#44aaff" },
  { name: "Fear", shape: "cone", sizeFt: 30, widthFt: 5, color: "#44aaff" },
  { name: "Fire Storm", shape: "square", sizeFt: 10, widthFt: 5, color: "#ff4400" },
  { name: "Fireball", shape: "circle", sizeFt: 20, widthFt: 5, color: "#ff4400" },
  { name: "Flame Strike", shape: "circle", sizeFt: 10, widthFt: 5, color: "#ff4400" },
  { name: "Flaming Sphere", shape: "circle", sizeFt: 20, widthFt: 5, color: "#ff4400" },
  { name: "Fog Cloud", shape: "circle", sizeFt: 20, widthFt: 5, color: "#44aaff" },
  { name: "Frost Fingers", shape: "cone", sizeFt: 15, widthFt: 5, color: "#66ccff" },
  { name: "Globe of Invulnerability", shape: "circle", sizeFt: 10, widthFt: 5, color: "#44aaff" },
  { name: "Glyph of Warding", shape: "circle", sizeFt: 20, widthFt: 5, color: "#66cc00" },
  { name: "Gravity Fissure", shape: "line", sizeFt: 100, widthFt: 5, color: "#cc66ff" },
  { name: "Gravity Sinkhole", shape: "circle", sizeFt: 20, widthFt: 5, color: "#cc66ff" },
  { name: "Gust of Wind", shape: "line", sizeFt: 60, widthFt: 10, color: "#44aaff" },
  { name: "Hallucinatory Terrain", shape: "square", sizeFt: 150, widthFt: 5, color: "#44aaff" },
  { name: "Healing Spirit", shape: "square", sizeFt: 5, widthFt: 5, color: "#44aaff" },
  { name: "Heroes' Feast", shape: "square", sizeFt: 10, widthFt: 5, color: "#44aaff" },
  { name: "Holy Aura", shape: "circle", sizeFt: 30, widthFt: 5, color: "#44aaff" },
  { name: "Hunger of Hadar", shape: "circle", sizeFt: 20, widthFt: 5, color: "#66cc00" },
  { name: "Hypnotic Pattern", shape: "square", sizeFt: 30, widthFt: 5, color: "#44aaff" },
  { name: "Ice Storm", shape: "circle", sizeFt: 20, widthFt: 5, color: "#aaaaaa" },
  { name: "Illusory Dragon", shape: "cone", sizeFt: 60, widthFt: 5, color: "#66cc00" },
  { name: "Incendiary Cloud", shape: "circle", sizeFt: 20, widthFt: 5, color: "#ff4400" },
  { name: "Insect Plague", shape: "circle", sizeFt: 20, widthFt: 5, color: "#aaaaaa" },
  { name: "Investiture of Flame", shape: "circle", sizeFt: 30, widthFt: 5, color: "#ff4400" },
  { name: "Investiture of Ice", shape: "circle", sizeFt: 10, widthFt: 5, color: "#66ccff" },
  { name: "Investiture of Stone", shape: "circle", sizeFt: 15, widthFt: 5, color: "#44aaff" },
  { name: "Investiture of Wind", shape: "square", sizeFt: 15, widthFt: 5, color: "#aaaaaa" },
  { name: "Jallarzi's Storm of Radiance", shape: "circle", sizeFt: 10, widthFt: 5, color: "#ffe066" },
  { name: "Laeral's Silver Lance", shape: "line", sizeFt: 120, widthFt: 5, color: "#cc66ff" },
  { name: "Leomund's Tiny Hut", shape: "circle", sizeFt: 10, widthFt: 5, color: "#44aaff" },
  { name: "Lightning Bolt", shape: "line", sizeFt: 100, widthFt: 5, color: "#f5d90a" },
  { name: "Maddening Darkness", shape: "circle", sizeFt: 60, widthFt: 5, color: "#ff66cc" },
  { name: "Maelstrom", shape: "circle", sizeFt: 30, widthFt: 5, color: "#aaaaaa" },
  { name: "Magic Circle", shape: "circle", sizeFt: 10, widthFt: 5, color: "#44aaff" },
  { name: "Magnify Gravity", shape: "circle", sizeFt: 10, widthFt: 5, color: "#cc66ff" },
  { name: "Mass Cure Wounds", shape: "circle", sizeFt: 30, widthFt: 5, color: "#44aaff" },
  { name: "Meteor Swarm", shape: "circle", sizeFt: 40, widthFt: 5, color: "#aaaaaa" },
  { name: "Mold Earth", shape: "square", sizeFt: 5, widthFt: 5, color: "#44aaff" },
  { name: "Moonbeam", shape: "circle", sizeFt: 5, widthFt: 5, color: "#ffe066" },
  { name: "Otiluke's Freezing Sphere", shape: "circle", sizeFt: 60, widthFt: 5, color: "#66ccff" },
  { name: "Prismatic Spray", shape: "cone", sizeFt: 60, widthFt: 5, color: "#66cc00" },
  { name: "Pulse Wave", shape: "cone", sizeFt: 30, widthFt: 5, color: "#cc66ff" },
  { name: "Purify Food and Drink", shape: "circle", sizeFt: 5, widthFt: 5, color: "#44aaff" },
  { name: "Pyrotechnics", shape: "circle", sizeFt: 20, widthFt: 5, color: "#44aaff" },
  { name: "Ravenous Void", shape: "circle", sizeFt: 20, widthFt: 5, color: "#cc66ff" },
  { name: "Reverse Gravity", shape: "circle", sizeFt: 50, widthFt: 5, color: "#44aaff" },
  { name: "Rime's Binding Ice", shape: "cone", sizeFt: 30, widthFt: 5, color: "#66ccff" },
  { name: "Shape Water", shape: "square", sizeFt: 5, widthFt: 5, color: "#44aaff" },
  { name: "Shatter", shape: "circle", sizeFt: 10, widthFt: 5, color: "#6f8bff" },
  { name: "Sickening Radiance", shape: "circle", sizeFt: 30, widthFt: 5, color: "#ffe066" },
  { name: "Silence", shape: "circle", sizeFt: 20, widthFt: 5, color: "#44aaff" },
  { name: "Sleep", shape: "circle", sizeFt: 5, widthFt: 5, color: "#44aaff" },
  { name: "Sleet Storm", shape: "circle", sizeFt: 40, widthFt: 5, color: "#44aaff" },
  { name: "Slow", shape: "square", sizeFt: 40, widthFt: 5, color: "#44aaff" },
  { name: "Snilloc's Snowball Swarm", shape: "circle", sizeFt: 5, widthFt: 5, color: "#66ccff" },
  { name: "Spellfire Storm", shape: "circle", sizeFt: 20, widthFt: 5, color: "#ffe066" },
  { name: "Spike Growth", shape: "circle", sizeFt: 20, widthFt: 5, color: "#aaaaaa" },
  { name: "Spirit Guardians", shape: "circle", sizeFt: 15, widthFt: 5, color: "#7a33aa" },
  { name: "Stinking Cloud", shape: "circle", sizeFt: 20, widthFt: 5, color: "#44aaff" },
  { name: "Storm Sphere", shape: "circle", sizeFt: 20, widthFt: 5, color: "#aaaaaa" },
  { name: "Sunbeam", shape: "line", sizeFt: 60, widthFt: 5, color: "#ffe066" },
  { name: "Sunburst", shape: "circle", sizeFt: 60, widthFt: 5, color: "#ffe066" },
  { name: "Sword Burst", shape: "circle", sizeFt: 5, widthFt: 5, color: "#cc66ff" },
  { name: "Symbol", shape: "circle", sizeFt: 60, widthFt: 5, color: "#7a33aa" },
  { name: "Synaptic Static", shape: "circle", sizeFt: 20, widthFt: 5, color: "#ff66cc" },
  { name: "Thunderwave", shape: "square", sizeFt: 15, widthFt: 5, color: "#6f8bff" },
  { name: "Transmute Rock", shape: "square", sizeFt: 40, widthFt: 5, color: "#aaaaaa" },
  { name: "Vitriolic Sphere", shape: "circle", sizeFt: 20, widthFt: 5, color: "#66cc00" },
  { name: "Wall of Fire (Line)", shape: "line", sizeFt: 60, widthFt: 10, color: "#ff4400" },
  { name: "Wall of Fire (Ring)", shape: "ring", sizeFt: 20, widthFt: 10, color: "#ff4400" },
  { name: "Watery Sphere", shape: "circle", sizeFt: 5, widthFt: 5, color: "#44aaff" },
  { name: "Web", shape: "square", sizeFt: 20, widthFt: 5, color: "#ff4400" },
  { name: "Weird", shape: "circle", sizeFt: 30, widthFt: 5, color: "#ff66cc" },
  { name: "Whirlwind", shape: "circle", sizeFt: 10, widthFt: 5, color: "#aaaaaa" },
  { name: "Wrath of Nature", shape: "square", sizeFt: 60, widthFt: 5, color: "#aaaaaa" },
  { name: "Zone of Truth", shape: "circle", sizeFt: 15, widthFt: 5, color: "#44aaff" },
];
