#!/usr/bin/env python3
# Regenerates src/map/lightSources.ts from the 5etools item and spell data.
import argparse
import glob
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "map", "lightSources.ts")
SOURCE_RANK = {"PHB": 0, "XPHB": 1}
HAND_ADDED = [("Darkvision 60 ft", 0, 60), ("Darkvision 120 ft", 0, 120)]

TAG = re.compile(r"\{@\w+ ([^|}]*)[^}]*\}")
RADIUS = re.compile(
    r"bright light in an? (\d+)-foot[- ]radius,? and dim light for an additional (\d+) feet", re.I
)
SPHERE = re.compile(
    r"(\d+)-foot-radius sphere.{0,200}?is bright light and sheds dim light for an additional (\d+) feet",
    re.I | re.S,
)
DIM_ONLY = re.compile(r"(?:sheds|shedding) dim light in an? (\d+)-foot radius", re.I)


def texts(node):
    if isinstance(node, str):
        yield TAG.sub(r"\1", node)
    elif isinstance(node, list):
        for child in node:
            yield from texts(child)
    elif isinstance(node, dict):
        for key in ("entries", "items", "entry"):
            if key in node:
                yield from texts(node[key])


def parse(text):
    for pattern in (RADIUS, SPHERE):
        m = pattern.search(text)
        if m:
            return int(m.group(1)), int(m.group(2))
    if not re.search(r"bright light", text, re.I):
        m = DIM_ONLY.search(text)
        if m:
            return 0, int(m.group(1))
    return None


def records(root):
    data = os.path.join(root, "5etools-data", "data")
    for name, key in (("items.json", "item"), ("items-base.json", "baseitem")):
        with open(os.path.join(data, name)) as f:
            yield from json.load(f).get(key, [])
    for path in sorted(glob.glob(os.path.join(data, "spells", "spells-*.json"))):
        with open(path) as f:
            yield from json.load(f).get("spell", [])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=os.path.join(HERE, "..", "..", "..", "dnd-library"))
    args = parser.parse_args()

    best = {}
    unmatched = set()
    for rec in records(args.root):
        text = " ".join(texts(rec.get("entries", [])))
        found = parse(text)
        if not found:
            if re.search(r"(bright|dim) light", text, re.I):
                unmatched.add(rec["name"])
            continue
        rank = SOURCE_RANK.get(rec.get("source"), 2)
        if rec["name"] not in best or rank < best[rec["name"]][0]:
            best[rec["name"]] = (rank, *found)

    for name in sorted(unmatched - best.keys()):
        print(f"unmatched: {name}", file=sys.stderr)

    entries = {name: (bright, dim) for name, (_, bright, dim) in best.items()}
    for name, bright, dim in HAND_ADDED:
        entries[name] = (bright, dim)

    lines = [
        "export interface LightSource {",
        "  name: string;",
        "  brightFt: number;",
        "  dimFt: number;",
        "}",
        "",
        "// Generated by scripts/gen-light-sources.py from the 5etools item and spell",
        "// data: every entry that sheds bright light in a radius plus dim light beyond",
        "// it (or dim light only). Darkvision 60 ft and 120 ft are hand-added and kept",
        "// in alphabetical order.",
        "export const LIGHT_SOURCES: LightSource[] = [",
    ]
    for name in sorted(entries, key=str.lower):
        bright, dim = entries[name]
        lines.append(f"  {{ name: {json.dumps(name)}, brightFt: {bright}, dimFt: {dim} }},")
    lines.append("];")
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {len(entries)} light sources", file=sys.stderr)


if __name__ == "__main__":
    main()
